spring:
  datasource:
    url: jdbc:mysql://192.168.1.150:3306/test?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.150
    password: 123456
    port: 6379
    database: 0
    timeout: 5000ms
    jedis:
      pool:
        max-active: 150
        max-idle: 100
        min-idle: 10
        max-wait: 3000ms

# https://gitee.com/baomidou/mybatisplus-spring-boot/blob/master/src/main/resources/application.yml
mybatis-plus:
  mapper-locations: classpath:/mapper/xml/*.xml, classpath:/mapper/*.xml
  typeAliasesPackage: com.xiyuan.bootcloud.mybatis.entity
  global-config:
    refresh-mapper: true
